export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"63b877e74a50a9001ffb6d9e",
				"63b877e74a50a9001ffb6da1"
			]
		},
		"63b877e74a50a9001ffb6d9e": {
			"id": "63b877e74a50a9001ffb6d9e",
			"name": "404",
			"pageUrl": "404"
		},
		"63b877e74a50a9001ffb6da1": {
			"id": "63b877e74a50a9001ffb6da1",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {},
		"seo": {
			"sitemapFileType": "autogenerated"
		}
	}
}